### ISSUE TITLE
Models not available

### ISSUE THREAD

**Issue by ykim362** [jungokasai/twist_decoding#1]
### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?

Hi @jungokasai 

Thanks a lot for the great work!

When I tried to download models and data, I got access errors.
Would you be able to make the files public?

Got this error :

Forbidden
You don't have permission to access /twist/domains/trans-base_medicine-de-en.tar.gz on this server.

**Comment by jungokasai** [comment]
Sorry for my late response! Do you mean: `https://arkdata.cs.washington.edu/twist/domains/trans-base_medicine-de-en.tar.gz`? I think it's open to public. Could you try:
```bash
wget https://arkdata.cs.washington.edu/twist/domains/trans-base_medicine-de-en.tar.gz
```

**Comment by ykim362** [comment]
Thank you so much! I can access the files now.
